# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings - Accessible via {{ site.myvariable }}.
title: "Víctor Gallego"
description: "Researcher in AI & Stats"
url: "https://vicgalle.github.io"
author: 
  name: "Victor Adolfo Gallego Alcala"
  url: "/"
github:
  repo: "https://github.com/vicgalle/vicgalle.github.io"
baseurl: /

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5

plugins: 
  - jekyll-gist
  - jekyll-paginate

